version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file: .env.local
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: .env.local
